baseURL = "https://www.cyberstudent.blog/"
languageCode = "en-us"
title = "Cyber Student"
theme = "cactus"

[params]

  colortheme = "white"
  description = "I enjoy learning about computers and networks. Every fortnight, I publish a post that goes over what I've learnt over that time in hopes that I can teach you something new." 
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://github.com/CyberStudentBlog"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup.goldmark.renderer]
unsafe= true

[[params.social]]
  name = "email"
  link = "dev@cyberstudent.blog"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/cyberstudent.blog/"
